version: "3"
services:
  andyyang.co.uk:
    image: ghost:latest
    container_name: ghost
    environment:
      - url=https://blog.com
    ports:
      - 8091:2368/tcp
    restart: always
    volumes:
      - ./content:/var/lib/ghost/content
