version: "3"
services:
  jackett:
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
    image: linuxserver/jackett:latest
    ports:
      - 9117:9117/tcp
    restart: unless-stopped
    volumes:
      - ./Config:/config
      - /portainer/Downloads:/downloads
