version: "3.4"

services:
  app:
    image: monica
    container_name: monica_app
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - APP_KEY=superSecretKey #generate a random 32 character string
      - DB_HOST=db
      - APP_URL=http://monica.lan # update it to your domain
      - MAIL_MAILER=smtp
      - MAIL_HOST=server.com
      - MAIL_PORT=465
      - MAIL_USERNAME=admin@mydomain.com
      - MAIL_PASSWORD=password
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_ADDRESS=email@mydomain.com
      - MAIL_FROM_NAME="Monica - Personal CRM"
      - APP_DISABLE_SIGNUP=false
      - APP_SIGNUP_DOUBLE_OPTIN=true
      - DAV_ENABLED=true
      - MFA_ENABLED=true
    volumes:
      - /volume1/docker/monica/data:/var/www/html/storage #update to your own path
    restart: always

  db:
    image: mysql:5.7
    container_name: monica_db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - /volume1/docker/monica/mysql:/var/lib/mysql #update to your own path
    restart: always
