version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: 'Password'
      ServerIP: 192.168.0.2
    volumes:
      - './pihole/:/etc/pihole/'
      - './dnsmasq.d/:/etc/dnsmasq.d/'
  # Recommended but not required (DHCP needs NET_ADMIN) https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #  cap_add:
  #    - NET_ADMIN
    restart: unless-stopped

# OPTIONAL SECTION - see https://github.com/ShiromMakkad/docker-pihole-sync
# Need to git clone the docker-pihole-sync repository first
  pihole-sync-receiver:
    build: ./docker-pihole-sync           # need to do custom build for rpi
    container_name: pihole-sync-receiver
    volumes:
      - './piholesync/root:/root'
      - './piholesync/etc-ssh:/etc/ssh/'
      - './pihole:/mnt/etc-pihole'
      - './dnsmasq./:/mnt/etc=dnsmasq.d'
    environment:
      - "NODE=receiver"
    ports:
      - "2222:22"
