version: '2' # version 2 is necessary. v3 does not support ipam

# Reference: https://www.reddit.com/r/synology/comments/gmfta3/pihole_5_on_synology_using_docker_simplified_with/

services:
 pihole:
   container_name: pihole
   image: pihole/pihole:latest
   networks:
     pihole_network:
       ipv4_address: 192.168.0.200 # Enter desired IP address (that's unused) for the pihole container
   #cap_add:
   #  - NET_ADMIN # add if using DHCP in pihole
   volumes:
     - "./pihole/:/etc/pihole/"
     - "./dnsmasq.d/:/etc/dnsmasq.d/"
   dns:
     - 127.0.0.1
     - 8.8.8.8
   ports:
     - 443/tcp
     - 53/tcp
     - 53/udp
     - 67/udp
     - 80/tcp
   environment:
     TZ: Europe/London
     ServerIP: 192.168.0.200     # Enter desired IP address (that's unused) for the pihole container
     WEBPASSWORD: ^y6yL5LY*4go^o # Choose your own admin portal password or comment out to auto-generate.
   restart: unless-stopped
   
 # See https://github.com/ShiromMakkad/docker-pihole-sync  
 pihole-sync-receiver:
   image: shirom/pihole-sync:latest
   container_name: pihole-sync-receiver
   volumes:
     - "./piholesync/root/:/root/"
     - "./piholesync/etc-ssh/:/etc/ssh/"
     - "./pihole/:/etc/pihole/"
     - "./dnsmasq.d/:/etc/dnsmasq.d/"
   environment:
     - "NODE=receiver"
   ports:
     - "2222:22"

networks:
 pihole_network:
   driver: macvlan
   driver_opts:
     parent: ovs_eth0               # type 'ifconfig' to find name of ethernet card
   ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1       # IP of your router/modem
         ip_range: 192.168.0.200/32 # Enter desired IP address (that's unused) for the pihole container
